server:
  port: 8086

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin22
    pool:
      enabled: true
      initial-size: 5
      max-size: 20


logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG